# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'opedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for opedia
  pod 'OGSwitch'
  pod 'CSV.swift', '~> 2.2.1'
end
